// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGHR.Models;

#nullable disable

namespace SIGHR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507094920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGHR.Models.Encomenda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstadoAtual")
                        .HasColumnType("bit");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<long>("UtilizadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId")
                        .IsUnique();

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("SIGHR.Models.Falta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFalta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UtilizadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId")
                        .IsUnique();

                    b.ToTable("Faltas");
                });

            modelBuilder.Entity("SIGHR.Models.Horario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EntradaAlmoco")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSaida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SaidaAlmoco")
                        .HasColumnType("datetime2");

                    b.Property<long>("UtilizadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId")
                        .IsUnique();

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("SIGHR.Models.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("SIGHR.Models.Requisicao", b =>
                {
                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<long>("EncomendaId")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint");

                    b.HasKey("MaterialId", "EncomendaId");

                    b.HasIndex("EncomendaId");

                    b.ToTable("Requisicoes");
                });

            modelBuilder.Entity("SIGHR.Models.Utilizadores", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PIN")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("SIGHR.Models.Encomenda", b =>
                {
                    b.HasOne("SIGHR.Models.Utilizadores", "Utilizadores")
                        .WithMany("Encomendas")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("SIGHR.Models.Falta", b =>
                {
                    b.HasOne("SIGHR.Models.Utilizadores", "Utilizadores")
                        .WithMany("Faltas")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("SIGHR.Models.Horario", b =>
                {
                    b.HasOne("SIGHR.Models.Utilizadores", "Utilizadores")
                        .WithMany("Horarios")
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizadores");
                });

            modelBuilder.Entity("SIGHR.Models.Requisicao", b =>
                {
                    b.HasOne("SIGHR.Models.Encomenda", "Encomenda")
                        .WithMany("Requisicoes")
                        .HasForeignKey("EncomendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGHR.Models.Material", "Material")
                        .WithMany("Requisicoes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encomenda");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SIGHR.Models.Encomenda", b =>
                {
                    b.Navigation("Requisicoes");
                });

            modelBuilder.Entity("SIGHR.Models.Material", b =>
                {
                    b.Navigation("Requisicoes");
                });

            modelBuilder.Entity("SIGHR.Models.Utilizadores", b =>
                {
                    b.Navigation("Encomendas");

                    b.Navigation("Faltas");

                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
